"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type ManagedEvent = { id: string; title: string; status: "draft" | "published"; startsAt: string; location: string; slug: string };
export function EventManager({ id }: { id: string }) {
  const router = useRouter(); const [event, setEvent] = useState<ManagedEvent | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [pendingAction, setPendingAction] = useState<"status" | "archive" | "">("");
  useEffect(() => { fetch(`/api/organizer/events/${id}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setEvent(data.event); }).catch((reason) => setError(reason.message)); }, [id]);
  async function setStatus(status: "draft" | "published") { setMessage(""); setError(""); setPendingAction("status"); try { const response = await fetch(`/api/events/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setEvent((current) => current ? { ...current, status } : current); setMessage(status === "published" ? "Event is live and visible to attendees." : "Event is now private and back in drafts."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Event could not be updated."); } finally { setPendingAction(""); } }
  async function archive() { if (!window.confirm(`Archive “${event?.title}”? It will leave your event list and attendees will no longer find its public page.`)) return; setPendingAction("archive"); setError(""); try { const response = await fetch(`/api/events/${id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); router.push("/organizer/dashboard"); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Event could not be archived."); setPendingAction(""); } }
  if (error && !event) return <div className="workspace-alert" role="alert">{error}</div>;
  if (!event) return <div className="workspace-loading manage-skeleton" role="status" aria-label="Loading event"><span /><span /><span /></div>;
  return <section className="manage-card" aria-busy={Boolean(pendingAction)}><div><span className={`status-label ${event.status}`}>{event.status}</span><h2>{event.title}</h2><p><time dateTime={event.startsAt}>{new Date(event.startsAt).toLocaleString()}</time> · {event.location}</p><div className="public-url"><span className="mono">PUBLIC URL</span><code>ticklit.com/events/{event.slug}</code></div></div><div className="manage-actions"><button type="button" className="button-link primary" disabled={Boolean(pendingAction)} onClick={() => setStatus(event.status === "draft" ? "published" : "draft")}>{pendingAction === "status" ? "Updating…" : event.status === "draft" ? "Publish event" : "Move to draft"}</button><button type="button" className="danger-button" disabled={Boolean(pendingAction)} onClick={archive}>{pendingAction === "archive" ? "Archiving…" : "Archive event"}</button></div>{error && <div className="form-alert" role="alert">{error}</div>}{message && <div className="form-alert success" role="status">{message}</div>}</section>;
}
