"use client";

import { useEffect, useState } from "react";
type Sales = { event: { title: string }; summary: { orders: number; tickets: number; gross: number }; orders: Array<{ id: string; attendeeName?: string; ticketCount?: number; total?: number; paymentStatus?: string; createdAt?: string }> };
export function SalesDashboard({ id }: { id: string }) {
  const [data, setData] = useState<Sales | null>(null); const [error, setError] = useState("");
  function load() { setError(""); fetch(`/api/organizer/events/${id}/sales`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); }).catch((reason) => setError(reason.message)); }
  useEffect(() => { fetch(`/api/organizer/events/${id}/sales`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); }).catch((reason) => setError(reason.message)); }, [id]);
  if (error) return <div className="workspace-alert" role="alert"><b>Sales data could not be loaded.</b><span>{error}</span><button className="button-link" type="button" onClick={load}>Try again</button></div>;
  if (!data) return <div className="workspace-loading metric-skeleton" role="status" aria-label="Loading sales"><span /><span /><span /></div>;
  return <><section className="metric-grid" aria-label="Sales summary"><div><span>Tickets sold</span><b>{data.summary.tickets}</b></div><div><span>Paid orders</span><b>{data.summary.orders}</b></div><div><span>Gross sales</span><b>AED {data.summary.gross.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</b></div></section><section className="order-table"><div className="table-heading"><div><span className="mono">LATEST ACTIVITY</span><h2>{data.event.title}</h2></div><span>{data.orders.length} {data.orders.length === 1 ? "order" : "orders"}</span></div>{data.orders.length ? <div className="order-list" role="table" aria-label="Paid orders"><div className="order-row order-row-head" role="row"><span role="columnheader">Attendee</span><span role="columnheader">Tickets</span><span role="columnheader">Total</span><span role="columnheader">Status</span></div>{data.orders.map((order) => <div className="order-row" role="row" key={order.id}><b role="cell">{order.attendeeName || "Attendee"}</b><span role="cell">{order.ticketCount || 0}</span><span role="cell">AED {Number(order.total || 0).toFixed(2)}</span><span role="cell" className={`status-label ${order.paymentStatus}`}>{order.paymentStatus || "pending"}</span></div>)}</div> : <div className="table-empty"><b>No orders yet</b><p>Paid orders will appear here as soon as guests check out.</p></div>}</section></>;
}
